### ISSUE TITLE
Addresses are being geocoded to Victoria

### ISSUE THREAD

**Issue by equivalentideas** [planningalerts-scrapers/logan#2] opened 2016-11-02 08:29 UTC
These ones for example:

https://www.planningalerts.org.au/applications/741805

https://www.planningalerts.org.au/applications/741784

https://www.planningalerts.org.au/applications/741781

https://www.planningalerts.org.au/applications/741782

**Comment by equivalentideas** [comment] 2016-11-02 08:35
I've switched off auto-run on the scraper on morph.io . Remember to turn this back on when it's fixed https://morph.io/planningalerts-scrapers/logan

**Comment by LoveMyData** [comment] 2017-04-13 03:18
@equivalentideas, I think this is not a bug of this scraper but a bug of PA itself.

Those address is in an area of new development and google have ZERO_RESULTS about those address.

Tested those address here https://developers.google.com/maps/documentation/geocoding/intro

We should be pretty safe to turn on Auto-Run again and fix PA. Not sure is it [related](https://github.com/openaustralia/planningalerts/issues/480)

**Comment by LoveMyData** [comment] 2017-04-13 03:18
FYI, I am updating the scraper to collect 'last month' data.

**Comment by henare** [comment] 2017-04-20 05:37
I'm trusting @LoveMyData and closing this :+1:

**Closed by henare** 2017-04-20 05:37 UTC
